In [1]:
import pandas as pd

In [4]:
df=pd.read_csv(r'C:\Users\SaaD WaHeeD\Desktop\archive\company_esg_financial_dataset.csv')

In [6]:
df.head()

,CompanyID,CompanyName,Industry,Region,Year,Revenue,ProfitMargin,MarketCap,GrowthRate,ESG_Overall,ESG_Environmental,ESG_Social,ESG_Governance,CarbonEmissions,WaterUsage,EnergyConsumption
0,1,Company_1,Retail,Latin America,2015,459.2,6.0,337.5,NaN,57.0,60.7,33.5,76.8,35577.4,17788.7,71154.7
1,1,Company_1,Retail,Latin America,2016,473.8,4.6,366.6,3.2,56.7,58.9,32.8,78.5,37314.7,18657.4,74629.4
2,1,Company_1,Retail,Latin America,2017,564.9,5.2,313.4,19.2,56.5,57.6,34.0,77.8,45006.4,22503.2,90012.9
3,1,Company_1,Retail,Latin America,2018,558.4,4.3,283.0,-1.1,58.0,62.3,33.4,78.3,42650.1,21325.1,85300.2
4,1,Company_1,Retail,Latin America,2019,554.5,4.9,538.1,-0.7,56.6,63.7,30.0,76.1,41799.4,20899.7,83598.8

In [10]:
dim_company=df[['CompanyID','CompanyName','Region','Industry']]

In [13]:
dim_company=dim_company.drop_duplicates(subset=['CompanyID'])

In [14]:
dim_company.head()

    CompanyID CompanyName         Region        Industry
0           1   Company_1  Latin America          Retail
11          2   Company_2           Asia          Retail
22          3   Company_3  Latin America  Transportation
33          4   Company_4         Africa      Technology
44          5   Company_5    Middle East         Finance

In [16]:
dim_company.isna().sum()

CompanyID      0
CompanyName    0
Region         0
Industry       0
dtype: int64

In [21]:
dim_company['Region'].unique()

array(['Latin America', 'Asia', 'Africa', 'Middle East', 'Oceania',
       'Europe', 'North America'], dtype=object)

In [23]:
dim_company['Industry'].unique()

array(['Retail', 'Transportation', 'Technology', 'Finance', 'Healthcare',
       'Energy', 'Consumer Goods', 'Utilities', 'Manufacturing'],
      dtype=object)

In [28]:
dim_company.to_csv(r'C:\Users\SaaD WaHeeD\Desktop\archive\dim_companytable.csv',index=False)

In [30]:
df.columns

Index(['CompanyID', 'CompanyName', 'Industry', 'Region', 'Year', 'Revenue',
       'ProfitMargin', 'MarketCap', 'GrowthRate', 'ESG_Overall',
       'ESG_Environmental', 'ESG_Social', 'ESG_Governance', 'CarbonEmissions',
       'WaterUsage', 'EnergyConsumption'],
      dtype='object')

In [34]:
Fact_Table=df[['CompanyID','Year','Revenue','ProfitMargin','MarketCap','GrowthRate','ESG_Overall','ESG_Environmental','ESG_Social','ESG_Governance','CarbonEmissions','WaterUsage','EnergyConsumption']]

In [36]:
Fact_Table.shape

(11000, 13)

In [37]:
Fact_Table.drop_duplicates()

,CompanyID,Year,Revenue,ProfitMargin,MarketCap,GrowthRate,ESG_Overall,ESG_Environmental,ESG_Social,ESG_Governance,CarbonEmissions,WaterUsage,EnergyConsumption
0,1,2015,459.2,6.0,337.5,NaN,57.0,60.7,33.5,76.8,35577.4,17788.7,71154.7
1,1,2016,473.8,4.6,366.6,3.2,56.7,58.9,32.8,78.5,37314.7,18657.4,74629.4
2,1,2017,564.9,5.2,313.4,19.2,56.5,57.6,34.0,77.8,45006.4,22503.2,90012.9
3,1,2018,558.4,4.3,283.0,-1.1,58.0,62.3,33.4,78.3,42650.1,21325.1,85300.2
4,1,2019,554.5,4.9,538.1,-0.7,56.6,63.7,30.0,76.1,41799.4,20899.7,83598.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10995,1000,2021,3419.2,21.7,14416.7,0.4,52.2,67.2,46.3,43.1,498875.8,623594.7,2494378.8
10996,1000,2022,3518.8,21.4,8078.9,2.9,51.9,68.7,44.7,42.3,506013.7,632517.1,2530068.4
10997,1000,2023,3417.1,17.1,13263.4,-2.9,52.9,72.4,43.1,43.2,473561.5,591951.9,2367807.7
10998,1000,2024,3183.2,15.7,6960.1,-6.8,52.0,72.4,40.5,42.9,441310.9,551638.6,2206554.3
10999,1000,2025,3173.5,17.5,5666.1,-0.3,51.8,74.5,39.7,41.4,430741.6,538427.0,2153707.9

In [38]:
df.isnull().sum()

CompanyID               0
CompanyName             0
Industry                0
Region                  0
Year                    0
Revenue                 0
ProfitMargin            0
MarketCap               0
GrowthRate           1000
ESG_Overall             0
ESG_Environmental       0
ESG_Social              0
ESG_Governance          0
CarbonEmissions         0
WaterUsage              0
EnergyConsumption       0
dtype: int64

In [40]:
Fact_Table['GrowthRate'].nunique()

562

In [41]:
Fact_Table['GrowthRate']

0         NaN
1         3.2
2        19.2
3        -1.1
4        -0.7
         ...
10995     0.4
10996     2.9
10997    -2.9
10998    -6.8
10999    -0.3
Name: GrowthRate, Length: 11000, dtype: float64

In [44]:
df[df['GrowthRate'].isnull()]['Year'].value_counts()

Year
2015    1000
Name: count, dtype: int64

In [45]:
Fact_Table.to_csv(r'C:\Users\SaaD WaHeeD\Desktop\archive\Fact_table.csv',index=False)